### ISSUE TITLE
Crud app edit error. MultiValueDictKeyError 'location'

### ISSUE THREAD

**Issue by dgleba** [gowthamand/django-crud-ajax-login-register-fileupload#11]
I get this error on edit in the crud app.

```
Request Method: | POST
-- | --
http://192.168.88.60:6465/edit/update/4
3.0.1
MultiValueDictKeyError
'location'
/usr/local/lib/python3.8/site-packages/django/utils/datastructures.py in __getitem__, line 78
/usr/local/bin/python
3.8.6
['/code',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/site-packages']
Sat, 10 Oct 2020 05:03:54 +0530
```
![image](https://user-images.githubusercontent.com/4622715/95639470-8a68d480-0a66-11eb-9c80-11710b34526f.png)

===
This picture is after add in crud app:
![image](https://user-images.githubusercontent.com/4622715/95639278-d49d8600-0a65-11eb-9344-7d5b4329abb6.png)

===
This is after pressing `edit`, not `add` as it says in the picture.
Notice the date is shown in location.
![image](https://user-images.githubusercontent.com/4622715/95639297-e717bf80-0a65-11eb-851c-07c49e9f819a.png)

**Comment by gowthamand** [comment]
wrong input data entered
