### ISSUE TITLE
could not create Table crud_member

### ISSUE THREAD

**Issue by socketpy** [gowthamand/django-crud-ajax-login-register-fileupload#2]
Hi there

I got some issues shown bellow:

ProgrammingError at /list
(1146, "Table 'djangocrud1.crud_member' doesn't exist")

Request Method: | GET
-- | --
http://localhost:8000/list
2.2.4
ProgrammingError

**Comment by gowthamand** [comment]
`python3 -m pip manage.py migrate crud`

Run above command

Problem is not migrated properly

**Comment by gowthamand** [comment]
Thanks for asking

`python3 -m pip manage.py migrate crud`

Run above command

Problem is not migrated properly
